### ISSUE TITLE
DictPlus().update(dict) works but dict.update(DictPlus()) doesn't

### ISSUE THREAD

**Issue by spencer-hanson** [spencer-hanson/dict-plus#3]
No keys are read from dict

**Comment by spencer-hanson** [comment]
DictPlus().update(dict) returns none?

**Comment by mccluret** [comment]
Yeah but I just added this function to dictplus you can push.

    def update(self, dictionary):
        for k, v in dictionary.iteritems():
            self[k] = v
        return self

**Comment by mccluret** [comment]
doesn't fix the dict.updated(dictplus) though

**Comment by spencer-hanson** [comment]
fixed in 0.2.0
